### ISSUE TITLE
Best Parameter about Bert base uncased

### ISSUE THREAD

**Issue by shuxiaobo** [jonathanherzig/commonsenseqa#3]
Hello @nalourie-ai2 Could you please release the best parameter to reproduce the result reported in the paper?

**Comment by nalourie-ai2** [comment]
Sure thing. The exact command used to train the model can be found in the [Running BERT](https://github.com/jonathanherzig/commonsenseqa#running-bert) section of the readme of this repo. It includes the hyper-parameters used for training.

The state of the art has been eclipsed though. The [RoBERTa](https://arxiv.org/abs/1907.11692) model gives highly competitive performance and you can find instructions for running it on CommonsenseQA [here](https://github.com/pytorch/fairseq/tree/master/examples/roberta/commonsense_qa).
