### ISSUE TITLE
How to run the fine tune script with multiple GPUs

### ISSUE THREAD

**Issue by allenyummy** [jonathanherzig/commonsenseqa#4]
Hi,

I add CUDA_VISIBLE_DEVICES=0,1,2 in front of the python run_commonsense_qa.py, and it is obvious that it still run the script with single GPU. 
(run nvidia-smi to check GPU usage)

How to run the fine tune script with multiple GPUs ?

Thanks for reply.

**Comment by nalourie-ai2** [comment]
All of our results were obtained by fine-tuning on TPUs, so multi-GPU usage is not supported.

If you're interested in multi-GPU training for BERT, the [transformers](https://github.com/huggingface/transformers) package from Hugging Face is a great resource for doing so.
