### ISSUE TITLE
Official website has crashed!!!

### ISSUE THREAD

**Issue by HAOChuzhan** [jonathanherzig/commonsenseqa#6]
Could you please tell me how long it will take for the website to be fixed, or is there another way to submit our model to leaderboard? Thank you!

**Comment by jonathanherzig** [comment]
Hi,
we are working to solve this issue. In the meantime you can submit model predictions for evaluation to jherzig@gmail.com

**Comment by jonathanherzig** [comment]
The website is back online. Sorry for the inconvenience!

**Comment by HAOChuzhan** [comment]
> jonathanherzig
Since we don't notice the information of github recently,  we sent the test prediction of our model until today. We hope to get the result as soon as possible. Thank you!
